// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(TestDBContext))]
    [Migration("20230715065349_satwika")]
    partial class satwika
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.AdminModel", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adminId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobileNumber");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("userRole");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("PK__AdminMod__AD0500A641BE4EE2");

                    b.ToTable("AdminModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.AdmissionModel", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"), 1L, 1);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<DateTime>("DateofJoining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("int")
                        .HasColumnName("instituteId");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("AdmissionId")
                        .HasName("PK__Admissio__705A8259EA167B94");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("AdmissionModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.CourseModel", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("CourseDescription")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("courseDescription");

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int")
                        .HasColumnName("courseDuration");

                    b.Property<string>("CourseName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("courseName");

                    b.Property<string>("CourseTiming")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("courseTiming");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("int")
                        .HasColumnName("instituteId");

                    b.Property<int?>("NumberofStudents")
                        .HasColumnType("int")
                        .HasColumnName("numberofStudents");

                    b.HasKey("CourseId")
                        .HasName("PK__CourseMo__2AA84FD10767D45B");

                    b.HasIndex("InstituteId");

                    b.ToTable("CourseModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.InstituteModel", b =>
                {
                    b.Property<int>("InstituteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instituteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstituteId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("imageUrl");

                    b.Property<string>("InstituteAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("instituteAddress");

                    b.Property<string>("InstituteDescription")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("instituteDescription");

                    b.Property<string>("InstituteName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("instituteName");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile");

                    b.HasKey("InstituteId")
                        .HasName("PK__Institut__AF018B2C2C390C5D");

                    b.ToTable("InstituteModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.LoginModel", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loginId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.HasKey("LoginId")
                        .HasName("PK__LoginMod__1F5EF4CF4AB45A19");

                    b.ToTable("LoginModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.ProgressModel", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("progressId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"), 1L, 1);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("progressPercentage");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("ProgressId")
                        .HasName("PK__Progress__0F2BDC7D48F8D384");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.RatingModel", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ratingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"), 1L, 1);

                    b.Property<string>("Comments")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("int")
                        .HasColumnName("instituteId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("RatingId")
                        .HasName("PK__RatingMo__2D290CA9A8440541");

                    b.HasIndex("InstituteId");

                    b.HasIndex("UserId");

                    b.ToTable("RatingModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("studentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AlternateMobile")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("alternateMobile");

                    b.Property<string>("AreaName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("areaName");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fatherName");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HouseNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("MotherName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("motherName");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("streetName");

                    b.HasKey("StudentId")
                        .HasName("PK__StudentM__4D11D63CD1C31FA0");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobileNumber");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("userRole");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__UserMode__CB9A1CFFB81ADADF");

                    b.ToTable("UserModel", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.AdmissionModel", b =>
                {
                    b.HasOne("dotnetapp.Models.CourseModel", "Course")
                        .WithMany("AdmissionModels")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Admission__cours__440B1D61");

                    b.HasOne("dotnetapp.Models.InstituteModel", "Institute")
                        .WithMany("AdmissionModels")
                        .HasForeignKey("InstituteId")
                        .HasConstraintName("FK__Admission__insti__4316F928");

                    b.HasOne("dotnetapp.Models.StudentModel", "Student")
                        .WithMany("AdmissionModels")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Admission__stude__45F365D3");

                    b.HasOne("dotnetapp.Models.UserModel", "User")
                        .WithMany("AdmissionModels")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Admission__userI__44FF419A");

                    b.Navigation("Course");

                    b.Navigation("Institute");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnetapp.Models.CourseModel", b =>
                {
                    b.HasOne("dotnetapp.Models.InstituteModel", "Institute")
                        .WithMany("CourseModels")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CourseMod__insti__2C3393D0");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("dotnetapp.Models.ProgressModel", b =>
                {
                    b.HasOne("dotnetapp.Models.CourseModel", "Course")
                        .WithMany("ProgressModels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ProgressM__cours__4AB81AF0");

                    b.HasOne("dotnetapp.Models.UserModel", "User")
                        .WithMany("ProgressModels")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ProgressM__userI__49C3F6B7");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnetapp.Models.RatingModel", b =>
                {
                    b.HasOne("dotnetapp.Models.InstituteModel", "Institute")
                        .WithMany("RatingModels")
                        .HasForeignKey("InstituteId")
                        .HasConstraintName("FK__RatingMod__insti__6FE99F9F");

                    b.HasOne("dotnetapp.Models.UserModel", "User")
                        .WithMany("RatingModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__RatingMod__userI__70DDC3D8");

                    b.Navigation("Institute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnetapp.Models.StudentModel", b =>
                {
                    b.HasOne("dotnetapp.Models.CourseModel", "Course")
                        .WithMany("StudentModels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__StudentMo__cours__37A5467C");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("dotnetapp.Models.CourseModel", b =>
                {
                    b.Navigation("AdmissionModels");

                    b.Navigation("ProgressModels");

                    b.Navigation("StudentModels");
                });

            modelBuilder.Entity("dotnetapp.Models.InstituteModel", b =>
                {
                    b.Navigation("AdmissionModels");

                    b.Navigation("CourseModels");

                    b.Navigation("RatingModels");
                });

            modelBuilder.Entity("dotnetapp.Models.StudentModel", b =>
                {
                    b.Navigation("AdmissionModels");
                });

            modelBuilder.Entity("dotnetapp.Models.UserModel", b =>
                {
                    b.Navigation("AdmissionModels");

                    b.Navigation("ProgressModels");

                    b.Navigation("RatingModels");
                });
#pragma warning restore 612, 618
        }
    }
}
